export const BNIClient: typeof bniClient;
export const OneGatePayment: typeof oneGatePayment;
export const SnapBI: typeof snapBI;
export const RDL: typeof RDL;
export const RDN: typeof RDN;
import bniClient from "./lib/bniClient.js";
import oneGatePayment from "./lib/api/oneGatePayment.js";
import snapBI from "./lib/api/snapBI.js";
import RDL from "lib/api/rdl.js";
import RDN from "lib/api/rdn.js";
